static const SSL_CIPHER cipher_aliases[] = {
  ...
  {0, SSL_TXT_CAESAR, 0, 0, 0, SSL_CAESAR, 0, 0, 0, 0, 0},
  ...
};

void ssl_load_ciphers(void) {
  ...
  ssl_cipher_methods[SSL_ENC_CAESAR_IDX] = EVP_get_cipherbyname(SN_caesar);
  ...
}

int ssl_cipher_get_evp(const SSL_SESSION *s, const EVP_CIPHER **enc, const EVP_MD **md, int *mac_pkey_type, int *mac_secret_size, SSL_COMP **comp) {
  ...
  switch (c->algorithm_enc) {
    ...
    case SSL_CAESAR:
      i = SSL_ENC_CAESAR_IDX;
      break;
    ...
  }
  ...
}

static void ssl_cipher_get_disabled(unsigned long *mkey, unsigned long *auth, unsigned long *enc, unsigned long *mac, unsigned long *ssl) {
  ...
  *enc |= (ssl_cipher_methods[SSL_ENC_CAESAR_IDX] == NULL) ? SSL_CAESAR : 0;
  ...
}

char *SSL_CIPHER_description(const SSL_CIPHER *cipher, char *buf, int len) {
  ...
  switch (alg_enc) {
    ...
    case SSL_CAESAR:
      enc = "CAESAR";
      break;
    ...
  }
  ...
}
